from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QDate

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 317)
        MainWindow.setProperty("fixedSize", QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(300, 10, 181, 16))
        self.status_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 280, 521, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(260, 31, 256, 171))
        self.listView.setObjectName("listView")
        self.btn_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(440, 210, 75, 24))
        self.btn_delete.setObjectName("btn_delete")
        self.status_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.status_label_2.setGeometry(QtCore.QRect(20, 10, 181, 16))
        self.status_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status_label_2.setObjectName("status_label_2")
        self.label_status_process = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_status_process.setGeometry(QtCore.QRect(180, 260, 231, 16))
        self.label_status_process.setText("")
        self.label_status_process.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_status_process.setObjectName("label_status_process")
        self.btn_select_files = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_select_files.setGeometry(QtCore.QRect(260, 210, 75, 24))
        self.btn_select_files.setObjectName("btn_select_files")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 30, 181, 170))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_start = QtWidgets.QLabel(parent=self.widget)
        self.label_start.setObjectName("label_start")
        self.verticalLayout.addWidget(self.label_start)
        self.date_start = QtWidgets.QDateEdit(parent=self.widget)
        self.date_start.setCalendarPopup(True)
        self.date_start.setObjectName("date_start")
        self.verticalLayout.addWidget(self.date_start)
        self.label_end = QtWidgets.QLabel(parent=self.widget)
        self.label_end.setObjectName("label_end")
        self.verticalLayout.addWidget(self.label_end)
        self.date_end = QtWidgets.QDateEdit(parent=self.widget)
        self.date_end.setCalendarPopup(True)
        self.date_end.setObjectName("date_end")
        self.verticalLayout.addWidget(self.date_end)
        self.chk_actualizar = QtWidgets.QCheckBox(parent=self.widget)
        self.chk_actualizar.setChecked(True)
        self.chk_actualizar.setObjectName("chk_actualizar")
        self.verticalLayout.addWidget(self.chk_actualizar)
        self.chk_verificar = QtWidgets.QCheckBox(parent=self.widget)
        self.chk_verificar.setChecked(True)
        self.chk_verificar.setObjectName("chk_verificar")
        self.verticalLayout.addWidget(self.chk_verificar)
        self.btn_process = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_process.setGeometry(QtCore.QRect(20, 210, 75, 24))
        self.btn_process.setObjectName("btn_process")
        self.btn_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(130, 210, 75, 24))
        self.btn_save.setObjectName("btn_save")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Set the start date to the first day of the current month
        current_date = QDate.currentDate()
        first_day_of_month = QDate(current_date.year(), current_date.month(), 1)
        self.date_start.setDate(first_day_of_month)

        # Set the end date to the current date
        self.date_end.setDate(current_date)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Consolidado Semanal"))
        self.status_label.setText(_translate("MainWindow", "Cantidad de Archivos"))
        self.btn_delete.setText(_translate("MainWindow", "Borrar"))
        self.status_label_2.setText(_translate("MainWindow", "Parametros"))
        self.btn_select_files.setText(_translate("MainWindow", "Seleccionar"))
        self.label_start.setText(_translate("MainWindow", "Fecha inicial:"))
        self.label_end.setText(_translate("MainWindow", "Fecha final:"))
        self.chk_actualizar.setText(_translate("MainWindow", "Actualizar base de datos"))
        self.chk_verificar.setText(_translate("MainWindow", "Verificar con base existente"))
        self.btn_process.setText(_translate("MainWindow", "Procesar"))
        self.btn_save.setText(_translate("MainWindow", "Guardar"))
